config/routes.rb
BodykitMe::Application.routes.draw do
    resources :aim_progresses

    resources :password_resets do
      member do
        get 'new'
      end
    end

    match 'workout_plan/log/:id' => 'workout_sessions#log_workout', :as => :log_workout

    resources :points

    root :to => 'public#index'

    resources :countries

    resources :public

    resources :addresses do
      member do
        get "user"
      end
    end

    resources :user_sessions

    resources :users do
      collection do
        post "check_username"
        post "check_email"
      end
    end
    get "login" => "user_sessions#new"
    get "logout" => "user_sessions#destroy"
    get "register" => "users#new"

    resources :workout_sessions do
      member do
        post 'update_session'
        post 'create_thrills'
      end
    end

    resources :categories

    resources :aims do
      member do
        put 'invert_active'
        post 'add_new_aim_pro'
      end
    end

    resources :units

    resources :workout_plans do
      member do
        post 'click'
        post 'addWorkOut'
        post 'add_tag'
        post 'copy'
        get 'read_only'
        put 'invert_active'
      end

    end

    resources :workout_days do
      member do
        post 'addExistingExercise'
        post 'add_new_exercise'
        post 'add_tag'
      end

    end

    resources :exercises

    resources :member_area

    get "dashboard" => "member_area#index"

    resources :create_plan_wizard do
      member do
        post 'add_new_day'
        post 'add_new_exercise'
      end
    end

end

app/controllers/member_area_controller.rb
class MemberAreaController < ApplicationController
  #require ""

  before_filter :authenticate

  # GET /member_area
  def index

    @user = current_user
    @aim =  Aim.where("is_active=? and user_id=?",true, current_user.id).find_all().first

    if !@aim.nil? && !@aim.aim_progresses.nil?
      @aimpro = AimProgress.where("aim_id=?", @aim.id).order('logging_date ASC').all
      @aim_value_start = formatDecimal(@aimpro.first.value, 2)
      @aim_value_actual = formatDecimal(@aimpro.last.value, 2)
      @aim_delta_actual = formatDecimal(@aimpro.last.value - @aimpro.first.value, 2)
      @aim_delta_goal = formatDecimal(@aim.value - @aimpro.last.value, 2)
      @aim_goal = @aim.value
    end

    @actual_workout_plan = WorkoutPlan.where("is_active=? and user_id=?",
                                             true, current_user.id).find_all().first

    @actual_workout_session = WorkoutSession.where("user_id=?",
                                                   current_user.id).order('date DESC').limit(1).find_all().first


    last3 = WorkoutSession.where("user_id=?",
                         current_user.id).order('date DESC').limit(3).find_all()
    #get 3 precedent of same drill
    exercises = Hash.new {|h,k| h[k] = [] }
    last3.each { |workout_session|
      #workout_session.exercises.each { |exercise|
        #exercises.join(exercise.id)
        #thrills = ExercisesWorkoutThrill.where("exercise_id=?", exercise.id).order('date DESC').limit(3).find_all()
      assemble_last_workouts(workout_session).each do |k,v|
          exercises[k] << v
      end
      #exercises.merge(assemble_last_workouts(workout_session).to_hash)
      #}
    }
    # exercises.distinct


    #assemble_last_workouts

  # render :text => exercises.to_s, :layout => false
  # return


    @last_workouts = exercises


    respond_to do |format|
      format.html # index.html.erb
      #format.json { render json: @aims }
    end
  end

  def assemble_last_workouts(workout_session)
    #@last_workout = Hash.new
    models = Hash.new
    workoutModel = WorkoutModel.new
    workout_session.exercises_workout_thrills.each { |thrill|
      if thrill.value.nil? && thrill.multiplier.nil?
        next
      end
      #thrills = Hash.new {|h,k| h[k] = [] }
      #thrills = @last_workout[thrill.exercise.name] << { :wdh => thrill.multiplier, :kg => thrill.value }

      # get correct workout
      workout = models[thrill.exercise.name] if models.has_key?(thrill.exercise.name)

      #if !workout.nil? #workout already there
      if models.has_key?(thrill.exercise.name)
        models[thrill.exercise.name].exerciseData << {:value => thrill.value, :multiplier => thrill.multiplier}
      else
        tmp = WorkoutModel.new
        tmp.name = thrill.exercise.name
        tmp.date = workout_session.date
        tmp.exerciseData = {}
        #tmp.exerciseData.store(:test, "testo")
        tmp.exerciseData = [{:value => thrill.value, :multiplier => thrill.multiplier}]
        models[thrill.exercise.name] = tmp
      end


      #workoutModel.name = thrill.exercise.name if workoutModel.name.nil?
      #workoutModel.date = @actual_workout_session.date if workoutModel.date.nil?
      #if workoutModel.exerciseData.nil?
      #  workoutModel.exerciseData =[{:value => thrill.value, :multiplier => thrill.multiplier}]
      #else
       # workoutModel.exerciseData << {:value => thrill.value, :multiplier => thrill.multiplier}
      #end

      #models[workoutModel.name] = workoutModel

      models
    }

    models
    #render :text => models.to_s, :layout => false
    #return

  end

  # GET /aims/1
  # GET /aims/1.json
  def show
    respond_to do |format|
      format.html # index.html.erb
                  #format.json { render json: @aims }
    end
  end

  def formatDecimal(value, count)
    return ("%."+count.to_s+"f") % value
  end
end

class WorkoutModel
  attr :name, true # benchpress
  attr :date, true # 01.02.2013
  attr :exerciseData, true # [{value, multiplier}]
end

app/helpers/member_area_helper.rb
module MemberAreaHelper
end

app/views/member_area/index.html.erb
<div id="aims">
  <% if !@aim.nil? %>
      <h2><%= @aim.name %></h2>

      <div class="row statistics">
        <div class="span4">
          <span class="lbl">Actual</span> <span class="value"><%= @aim_value_actual %> Kg</span>
            <span class="note green">
                <%
                   if @aim_delta_actual.to_f > 0
                     concat "+" + @aim_delta_actual.to_s
                   else
                     concat "-" + @aim_delta_actual.to_s
                   end
                %> Kg
            </span>
        </div>
        <div class="span4">
          <span class="lbl">Start</span> <span class="value"><%= @aim_value_start %> Kg</span>
        </div>
        <div class="span4">
          <span class="lbl">Goal</span> <span class="value"><%= @aim_goal %> Kg</span>
            <span class="note gray"><%
               if @aim_delta_goal.to_f > 0
                 concat "+" + @aim_delta_goal.to_s
               else
                 concat "-" + @aim_delta_goal.to_s
               end
            %> Kg left
            </span>
        </div>
      </div>
      <div id="chart_div">
        <%= image_tag "ajax-loader.gif" %>
      </div>
      <div class="aim_controls">
        <%= link_to image_tag("add_32.png", :border => 0), aim_path(@aim.id) %>
        <%= link_to image_tag("chart_32.png", :border => 0), aim_path(@aim.id) %>
      </div>
  <% end %>
</div>

<div id="quote">
  <div class="quote-img">
    <%= image_tag("quote.jpg") %>
  </div>
  <span>This is a super motivating Quote! Go out there and Squat this shit away mate!"</span>
  <small>- Pascal F. Bonds</small>
  <div class="clear"></div>
</div>

<div class="row-fluid">
  <div class="span6">
    <h2>Last workout</h2>
    <% if !@actual_workout_session.nil? %>
    <h3><%= @actual_workout_session.workout_day.day %></h3>
    <small><%= @actual_workout_session.date.strftime(('%d-%b-%Y %H:%M %z')) %></small>
        <% @last_workouts.each do | key, workout |  %>
            <div class="well">
              <p>Name: <%= key %></p>
              <% workout.reverse_each do | model | %>
                  <div style="background: lightblue; margin-right:10px; float: left">
                    <p><%= model.date.strftime(('%d %b %Y')) %></p>
                      <% model.exerciseData.each do | data | %>
                          <div>
                              <p>Wdh: <%= data[:multiplier] %></p>
                              <p>Kg: <%= data[:value] %></p>
                          </div>
                      <% end %>
                  </div>
              <% end %>
              <div style="clear:both;"></div>
            </div>
        <% end %>
    <% end %>
  </div>
  <div class="span6">
    <h2>Followers</h2>
    <h2>Badges</h2>
  </div>
</div>

<div class="row-fluid">
  <div class="span6">
    <div class="well">
      <!-- Ziele -->
      <span style="font-size:36px;">Ziele <br/></span>

      <% if @aim.nil? %>

          <br/>

          <p> Hier kannst du ein
            <%= link_to "Ziel definieren", new_aim_path %>.


      <% else %>

          Aktuelles Ziel: <%= @aim.name %> <br/>

          <% if @aim.aim_progresses.empty? %>

              <br/>

              <p> Du hast keine geloggten Zielfortschritte!<br/>
                Lege jetzt ein <%= link_to "Zielfortschritt", aim_path(@aim.id) %>an.
              </p>
          <% else %>

              <br/>

              <p>Ziel: <%= @aim.category.name %> <%= @aim.value %> <%= if !@aim.category.unit.nil? then @aim.category.unit.name end %>

              <p/>
              <!--<div id="chart_div"></div>-->

              Leg ein weiteren <%= link_to "Zielfortschritt", aim_path(@aim.id) %> an.
          <% end %>

      <% end %>
    </div>
    <div class="well">
      <!-- Workout_Sessions -->
      <span style="font-size:36px;">Trainings Sessions<br/></span>

      <% if !@actual_workout_session.nil? %>

          <br/>
          Letzte Trainings Session:
          <br/>
          <br/>
          <!-- table -->
          <p>
          <table class="table table-condensed">
            <thead>
            <tr>
              <th>Datum</th>
              <th>Trainingstag</th>
            </tr>
            </thead>
            <tbody>
            <tr>
              <td><%= link_to @actual_workout_session.date.strftime("%d.%m.%Y"), workout_session_path(@actual_workout_session.id) %></td>
              <td><%= @actual_workout_session.workout_day.day %></td>
            </tr>
            </tbody>
          </table>
      <% else %>
          <br/>
          Suche dir ein Tag im <%= link_to "Trainingsplan-Bereich!", workout_plans_path %> aus.
      <% end %>


    </div>
  </div>
  <div class="well span6">
    <!-- Workout_Plan -->
    <span style="font-size:36px;">Trainingspläne<br/></span>

    <% if !@actual_workout_plan.nil? %>


        <br/>

        <p> Aktueller
          Trainingsplan: <%= link_to @actual_workout_plan.name, workout_plan_path(@actual_workout_plan.id) %></p>

        <br/>
        <!-- table -->
        <p>
        <table class="table table-condensed">
          <thead>
          <tr>
            <th>Trainingstage</th>
          </tr>
          </thead>
          <tbody>
          <% @actual_workout_plan.workout_days.each_with_index do |day| %>
              <tr>
                <td><%= link_to day.day, log_workout_path(:id => day.id) %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
        <p/>

    <% else %>

        Der Wizzard:
        <%= link_to ">Wizzard!", raw("create_plan_wizard") %>

    <% end %>
  </div>
</div>

<!--<span style="font-size:36px;"><%= link_to "Log Workout Now!", new_workout_session_path %></span>
<p>What can I do further?</p>
<p>Statistics, Aims, Progress, etc...</p>
-->
<% if !@aim.nil? %>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>

    <script type="text/javascript">
        google.load("visualization", "1", {packages:["corechart"]});

        google.setOnLoadCallback(drawChart);

        function drawChart() {
            var data = new google.visualization.DataTable();
            data.addColumn("string", "Date");
            data.addColumn("number", "Weight");
            data.addColumn("number", "Goal");
            data.addColumn({ type:"boolean", role:"certainty" });

            data.addRows([
                <%
                size = @aim.aim_progresses.size
                index = 0
                @aimpro.each do | pro | %>
                <%if index < size %>
                ['<%= pro.logging_date.strftime("%d.%m") %>', <%= pro.value %>, <%= @aim.value %>, false],
                <% else %>
                ['<%= pro.logging_date.strftime("%d.%m") %>', <%= pro.value %>, <%= @aim.value %>, false]

                <% index =+ index %>
                <% end %>
                <% end %>
            ])

            var options = {

                width:940, height:300, vAxis:{ maxValue: <%= (@aim.value * 1.05).to_int %> },
                hAxis:{viewWindow:{min:0.5, max: <%= @aimpro.size - 0.4 %>}},
                legend:{ position:'in', alignment:'center' },
                chartArea:{
                    left:40,
                    bottom:60,
                    width:900,
                    height:230
                },
                series:{
                    1:{areaOpacity:0}
                },
                //title: 'Ziel: <%= @aim.name %>, Category: <%= if !@aim.category.unit.nil? then @aim.category.name end %>'
            };

            var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));
            chart.draw(data, options);
        }

    </script>
<% end %>