config/routes.rb
BodykitMe::Application.routes.draw do
    resources :aim_progresses

    resources :password_resets do
      member do
        get 'new'
      end
    end

    match 'workout_plan/log/:id' => 'workout_sessions#log_workout', :as => :log_workout

    resources :points

    root :to => 'public#index'

    resources :countries

    resources :public

    resources :addresses do
      member do
        get "user"
      end
    end

    resources :user_sessions

    resources :users do
      collection do
        post "check_username"
        post "check_email"
      end
    end
    get "login" => "user_sessions#new"
    get "logout" => "user_sessions#destroy"
    get "register" => "users#new"

    resources :workout_sessions do
      member do
        post 'update_session'
        post 'create_thrills'
      end
    end

    resources :categories

    resources :aims do
      member do
        put 'invert_active'
        post 'add_new_aim_pro'
      end
    end

    resources :units

    resources :workout_plans do
      member do
        post 'click'
        post 'addWorkOut'
        post 'add_tag'
        post 'copy'
        get 'read_only'
        put 'invert_active'
      end

    end

    resources :workout_days do
      member do
        post 'addExistingExercise'
        post 'add_new_exercise'
        post 'add_tag'
      end

    end

    resources :exercises

    resources :member_area

    get "dashboard" => "member_area#index"

    resources :create_plan_wizard do
      member do
        post 'add_new_day'
        post 'add_new_exercise'
      end
    end

end

app/models/workout_day.rb
class WorkoutDay < ActiveRecord::Base
  has_many :tags, :as => :taggable
  has_and_belongs_to_many :exercises
  belongs_to :workout_plan
  belongs_to :user
  has_one :workout_session
end

app/controllers/workout_days_controller.rb
class WorkoutDaysController < ApplicationController

  before_filter :authenticate

  def assign_exercises_selection_list
    @global_exercises_selection_list = Exercise.find_all_by_is_global(true).collect { |exercise|
      [exercise.name, exercise.id]
    }
    @exercises_selection_list = Exercise.find_all_by_user_id(current_user.id).collect { |exercise|
      [exercise.name, exercise.id]
    }
  end

  # GET /workout_days
  # GET /workout_days.json
  def index
    @workout_days = WorkoutDay.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @workout_days }
    end
  end

  # GET /workout_days/1
  # GET /workout_days/1.json
  def show
    @workout_day = WorkoutDay.find(params[:id])

    @exercises = @workout_day.exercises

    assign_exercises_selection_list

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @workout_day }
    end
  end

  # GET /workout_days/new
  # GET /workout_days/new.json
  def new
    @workout_day = WorkoutDay.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @workout_day }
    end
  end

  # GET /workout_days/1/edit
  def edit
    @workout_day = WorkoutDay.find(params[:id])
  end

  #POST /workout_days/1/add_new_exercise'
  def add_new_exercise
    @workout_day = WorkoutDay.find(params[:id])
    exercise = Exercise.create( :name => params[:exercise][:name],
                                :description => params[:exercise][:description],
                                :user_id => current_user.id)

    if !exercise.nil?
      @workout_day.exercises << exercise
    end

    @workout_day.save

    respond_to do |format|
      format.html { redirect_to @workout_day, notice: 'Exercise successfully added' }
      format.json { render json: @workout_day, status: :created, location: @workout_day }
    end
  end

  #POST /workout_days/1/add_tag
  def add_tag
    @workout_day = WorkoutDay.find(params[:id])
    tag = Tag.create(:name => params[:tag][:name])
    @workout_day.tags << tag

    @workout_day.save

    respond_to do |format|
      format.html { redirect_to @workout_day, notice: 'Successfully tagged' }
    end
  end

  #POST /workout_days/1/addExercise'
  #POST /workout_days/1/addExercise.json'
  def addExistingExercise
    @workout_day = WorkoutDay.find(params[:id])
    exerciseId = params[:exercise][:id]

    exercise = Exercise.find(exerciseId)

    if !exercise.nil?
      @workout_day.exercises << exercise
    end

    @workout_day.save

    respond_to do |format|
        format.html { redirect_to @workout_day, notice: 'Exercise successfully added' }
        format.json { render json: @workout_day, status: :created, location: @workout_day }
    end
  end

  # POST /workout_days
  # POST /workout_days.json
  def create
    @workout_day = WorkoutDay.new(params[:workout_day])
    @workout_day.user_id = current_user.id

    respond_to do |format|
      if @workout_day.save
        format.html { redirect_to @workout_day, notice: 'Workout day was successfully created.' }
        format.json { render json: @workout_day, status: :created, location: @workout_day }
      else
        format.html { render action: "new" }
        format.json { render json: @workout_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /workout_days/1
  # PUT /workout_days/1.json
  def update
    @workout_day = WorkoutDay.find(params[:id])

    respond_to do |format|
      if @workout_day.update_attributes(params[:workout_day])
        format.html { redirect_to @workout_day, notice: 'Workout day was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @workout_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workout_days/1
  # DELETE /workout_days/1.json
  def destroy
    @workout_day = WorkoutDay.find(params[:id])
    @workout_day.destroy

    respond_to do |format|
      format.html { redirect_to workout_days_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/workout_days_helper.rb
module WorkoutDaysHelper
end

app/views/workout_days/_form.html.erb
<%= form_for(@workout_day) do |f| %>
  <% if @workout_day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout_day.errors.count, "error") %> prohibited this workout_day from being saved:</h2>

      <ul>
      <% @workout_day.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day %><br />
    <%= f.text_field :day %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workout_days/edit.html.erb
<h1>Editing workout_day</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout_day %> |
<%= link_to 'Back', workout_days_path %>

app/views/workout_days/index.html.erb
<h1>Listing workout_days</h1>

<table>
  <tr>
    <th>Day</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @workout_days.each do |workout_day| %>
  <tr>
    <td><%= workout_day.day %></td>
    <td><%= link_to 'Show', workout_day %></td>
    <td><%= link_to 'Edit', edit_workout_day_path(workout_day) %></td>
    <td><%= link_to 'Destroy', workout_day, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Workout day', new_workout_day_path %>

app/views/workout_days/new.html.erb
<h1>New workout_day</h1>

<%= render 'form' %>

<%= link_to 'Back', workout_days_path %>

app/views/workout_days/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Day:</b>
  <%= @workout_day.day %>
</p>
<p>
  <b>Exercises:</b><br />
  <% @exercises.each do |e| %>
    <hr/>
    <%= link_to e.name, e %>  <br />
    Beschreibung: <%= e.description %><br/>
  <% end %>
</p>
<hr />
<p>
  <strong>Add existing exercise from Global: </strong><br />
  <%= form_tag addExistingExercise_workout_day_path do %>
  <%= select("exercise", "id", @global_exercises_selection_list, {:prompt => "Select a Exercise"}) %>
  <%= submit_tag 'add' %>
  <% end %>
  <br />
  <strong>Add your own existing exercise: </strong><br />
  <%= form_tag addExistingExercise_workout_day_path do %>
  <%= select("exercise", "id", @exercises_selection_list, {:prompt => "Select a Exercise"}) %>
  <%= submit_tag 'add' %>
  <% end %>
  <br />
  <br />
  <em>OR add a new exercise</em><br/>
  <%= form_tag add_new_exercise_workout_day_path do %>
  Name: <br/><%= text_field "exercise", "name" %> <br/>
  Description:<br/> <%= text_area "exercise", "description" %> <br/>
  <%= submit_tag 'add' %>
  <% end %>
</p>
<hr/>
<p>Tags:</p>
<p>
  <% @workout_day.tags.each do |t| %>
  <%= t.name %>
  <% end %>
</p>
<p>
  Add:
  <%= form_tag add_tag_workout_day_path do %>
    <%= text_field "tag", "name" %>
    <%= submit_tag 'add' %>
  <% end %>
</p>


<%= link_to 'Edit', edit_workout_day_path(@workout_day) %> |
<%= link_to 'Back', workout_days_path %>