config/routes.rb
BodykitMe::Application.routes.draw do
    resources :aim_progresses

    resources :password_resets do
      member do
        get 'new'
      end
    end

    match 'workout_plan/log/:id' => 'workout_sessions#log_workout', :as => :log_workout

    resources :points

    root :to => 'public#index'

    resources :countries

    resources :public

    resources :addresses do
      member do
        get "user"
      end
    end

    resources :user_sessions

    resources :users do
      collection do
        post "check_username"
        post "check_email"
      end
    end
    get "login" => "user_sessions#new"
    get "logout" => "user_sessions#destroy"
    get "register" => "users#new"

    resources :workout_sessions do
      member do
        post 'update_session'
        post 'create_thrills'
      end
    end

    resources :categories

    resources :aims do
      member do
        put 'invert_active'
        post 'add_new_aim_pro'
      end
    end

    resources :units

    resources :workout_plans do
      member do
        post 'click'
        post 'addWorkOut'
        post 'add_tag'
        post 'copy'
        get 'read_only'
        put 'invert_active'
      end

    end

    resources :workout_days do
      member do
        post 'addExistingExercise'
        post 'add_new_exercise'
        post 'add_tag'
      end

    end

    resources :exercises

    resources :member_area

    get "dashboard" => "member_area#index"

    resources :create_plan_wizard do
      member do
        post 'add_new_day'
        post 'add_new_exercise'
      end
    end

end

app/models/aim.rb
class Aim < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :aim_progresses
end

app/controllers/aims_controller.rb
class AimsController < ApplicationController

  before_filter :authenticate

  # GET /aims
  # GET /aims.json
  def index
    @aims = Aim.find_all_by_user_id(current_user.id)

    category = @aims.collect { | e |
      e.category ? [e.id, e.category.name] : [e.id, "no Category specified"]
    }
    @categories = Hash[*(category.flatten)]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @aims }
    end
  end

  # GET /aims/1
  # GET /aims/1.json
  def show
    @aim = Aim.find(params[:id])
    @aim_progress = AimProgress.new

    if !user_is_allowed?(@aim)
      redirect_to aims_path
      return
    end

    @category = @aim.category

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @aim }
    end
  end

  # GET /aims/new
  # GET /aims/new.json
  def new
    @aim = Aim.new

    assign_category_selection_list

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @aim }
    end
  end

  def assign_category_selection_list

    @category_selection_list = []

    if  !Category.all.empty?
      @category_selection_list = Category.all.collect {|category| [ category.name, category.id ] }

    end

  end

  # GET /aims/1/edit
  def edit
    @aim = Aim.find(params[:id])
    if !user_is_allowed?(@aim)
      redirect_to aims_path
      return
    end

    assign_category_selection_list
  end

  # POST /aims
  # POST /aims.json
  def create
    @aim = Aim.new(params[:aim])
    @aim.user = current_user

    respond_to do |format|
      if @aim.save
        format.html { redirect_to @aim, notice: 'Aim was successfully created.' }
        format.json { render json: @aim, status: :created, location: @aim }
      else
        format.html { render action: "new" }
        format.json { render json: @aim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /aims/1
  # PUT /aims/1.json
  def update
    @aim = Aim.find(params[:id])
    if !user_is_allowed?(@aim)
      redirect_to aims_path
      return
    end

    respond_to do |format|
      if @aim.update_attributes(params[:aim])
        format.html { redirect_to @aim, notice: 'Aim was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @aim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aims/1
  # DELETE /aims/1.json
  def destroy
    @aim = Aim.find(params[:id])
    if !user_is_allowed?(@aim)
      redirect_to aims_path
      return
    end
    @aim.destroy

    respond_to do |format|
      format.html { redirect_to aims_url }
      format.json { head :no_content }
    end
  end

  def user_is_allowed?(aim)
    if aim.user_id.equal?(current_user.id)
      return true
    else
      return false
    end
  end

  #PUT /aims/1/invert_active
  def invert_active
    @aim = Aim.find(params[:id])
    @aim.is_active = !@aim.is_active?

    @aim.save!

    respond_to do |format|
      format.html { redirect_to aims_path, notice: 'Successfully de-/activated' }
      format.json { render json: @aim, status: :created, location: @aim }
    end
  end

  #TO:DO
  #def de_active
  # // nur einer is  true oder keiner!
  #end


  def add_new_aim_pro
    @aim = Aim.find(params[:id])

    #render :text => params[:aim_progress][:date], :layout => false
    #return

    if params[:aim_progress_value].blank?

    else
      @aim_progress = AimProgress.new
      @aim_progress.value = params[:aim_progress_value]
      @aim_progress.logging_date = params[:aim_progress_logging_date].to_time
      @aim_progress.aim_id = params[:id]
      @aim_progress.save!

      #render :text => @aim_progress.to_json, :layout => false
      #return

      @aim.aim_progresses << @aim_progress

      @aim.save!

    end

    redirect_to aim_path()
  end

  def invert_active
    @aim = Aim.find(params[:id])


    @aim.is_active = !@aim.is_active?

    #render :text => @aim.name, :layout => false
    #return

    @aim.save!

    respond_to do |format|
      format.html { redirect_to aims_path, notice: 'Successfully de-/activated' }
      format.json { render json: @aim, status: :created, location: @aim }
    end
  end

end

app/helpers/aims_helper.rb
module AimsHelper
end

app/views/aims/_form.html.erb
<%= form_for(@aim) do |f| %>
  <% if @aim.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aim.errors.count, "error") %> prohibited this aim from being saved:</h2>

      <ul>
      <% @aim.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

    <div class="field">
      <%= f.label :value %><br />
      <%= f.text_field :value %>
    </div>

   <div class="field">
     <%= f.label :category_id %><br />
     <%= select("aim", "category_id", @category_selection_list,
                 {:prompt =>  "Select Category"  } ) %>
   </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aims/edit.html.erb
<h1>Editing aim</h1>

<%= render 'form' %>

<%= link_to 'Show', @aim %> |
<%= link_to 'Back', aims_path %>

app/views/aims/index.html.erb
<h1>Aims</h1>

<% @aims.each_with_index do |aim, index| %>
    <div class=" alert  <%= "alert-success" if aim.is_active?%>">

      <% if aim.is_active? %>
          <%= button_to 'Deactivate Plan', invert_active_aim_path(aim), method: :put, class: 'btn btn-danger pull-right' %>
      <% else %>
          <%= button_to 'Activate Plan', invert_active_aim_path(aim), method: :put, class: 'btn btn-success pull-right' %>
      <% end %>

      <h2>
        <%= link_to aim.name, aim %>
        <a href="#" data-toggle="collapse" data-target="#details-<%= index.to_s%>" onclick="changeToggle('',<%=index%>);return false">
          <%
             toggleState = 'toggleDown'
             if aim.is_active?
               toggleState = 'toggleUp'
             end
          %>
          <span id="toggler-<%=index%>" class="<%=toggleState%>"></span>
        </a>
      </h2>

      <div id="details-<%= index.to_s%>" class="collapse <%= 'in' if aim.is_active?%>">
        <% if aim.aim_progresses.empty? %>
            <p>No Progresses added yet. <%= link_to 'Add Progress now!', aim  %></p>
        <% else %>
            <!-- table -->
            <table class="table table-condensed">
              <thead>
              <tr>
                <th>Datum</th>
                <th>Value</th>
              </tr>
              </thead>
              <tbody>
              <% aim.aim_progresses.each_with_index do |pro| %>
                  <tr>
                  <td><%= link_to pro.logging_date.strftime("%d.%m.%Y") , edit_aim_progress_path(:id => pro.id)%></td>
                  <td><%= pro.value %> <%= if !aim.category.nil? then aim.category.unit.name end %> </td>
                  </tr>
              <% end %>
              </tbody>
            </table>


           <!-- <% aim.aim_progresses.each_with_index do |pro, index| %>
                <div class="well" style="float:left;width:250px;color:black;margin-right:6px;">
                  <a href="<%= aim_progress_path(:id => pro.id)%>"
                     class="btn pull-right log-workout-tip <%= "disabled" if !aim.is_active? %>"
                     rel="tooltip" title="Log your workout for <%= pro.id %>">
                    <i class="icon-edit"></i>
                  </a>
                  <h3><%= pro.id %></h3>
                </div>
            <% end %>
            -->

                <% if ((index+1) % 3) == 0 %>
                    <div class="clearfix"></div>
                <% end %>
        <% end %>
        <div class="clearfix"></div>

      </div>
    </div>
<% end %>

<hr/>
<%= link_to 'CREATE NEW AIM', new_aim_path %>

<script type="text/javascript">
    function changeToggle(prefix, i) {
        if(prefix != "") {
            prefix = prefix + "-"
        }
        elem = $("#toggler-" + prefix + i);
        if (elem.hasClass("toggleUp")) {
            elem.attr("class", "toggleDown")
        } else {
            elem.attr("class", "toggleUp")
        }
    };

    $(document).ready(function() {
        $(".log-workout-tip").tooltip({delay: { show: 1000, hide: 100 }});
    });
</script>

app/views/aims/new.html.erb
<h1>New aim</h1>

<%= render 'form' %>

<%= link_to 'Back', aims_path %>

app/views/aims/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @aim.name %>
</p>

<p>
  <b>Value:</b>
  <%= @aim.value %>
</p>

<p>
  <b>Category:</b>
  <%=
      if !@category.nil?
        link_to @category.name, @category
      end
  %>
</p>
<hr>
<p>
  <b>Aim Progresses:</b>
  <% if !(@aim.aim_progresses.nil?)  %>

      <!-- table -->
    <table class="table table-condensed">
      <thead>
      <tr>
        <th>Datum</th>
        <th>Value</th>
      </tr>
      </thead>
      <tbody>
      <% @aim.aim_progresses.each_with_index do |pro| %>
          <tr>
            <td><%= link_to pro.logging_date.strftime("%d.%m.%Y") , edit_aim_progress_path(:id => pro.id)%></td>
            <td><%= pro.value %> <%= if !@aim.category.unit.nil? then @aim.category.unit.name end %> </td>
          </tr>
      <% end %>
      </tbody>
    </table>

  <% end %>

</p>

<hr>

<b>Add a Progress</b>

<%= form_tag add_new_aim_pro_aim_path do %>
    Value: <%= text_field_tag "aim_progress_value"%>
    Date: <%= text_field_tag "aim_progress_logging_date"%>
    <%= hidden_field_tag "aim", :id => @aim.id%>
    <%= submit_tag 'add', :class => 'btn btn-primary' %>
<% end %>




<%= link_to 'Edit', edit_aim_path(@aim) %> |
<%= link_to 'Back', aims_path %>

<script type="text/javascript">
    $(document).ready(function () {


        $("#aim_progress_logging_date").datepicker({
            setDate: new Date(),
            dateFormat : 'dd.mm.yy'
        })

    });

</script>