config/routes.rb
BodykitMe::Application.routes.draw do
    resources :aim_progresses

    resources :password_resets do
      member do
        get 'new'
      end
    end

    match 'workout_plan/log/:id' => 'workout_sessions#log_workout', :as => :log_workout

    resources :points

    root :to => 'public#index'

    resources :countries

    resources :public

    resources :addresses do
      member do
        get "user"
      end
    end

    resources :user_sessions

    resources :users do
      collection do
        post "check_username"
        post "check_email"
      end
    end
    get "login" => "user_sessions#new"
    get "logout" => "user_sessions#destroy"
    get "register" => "users#new"

    resources :workout_sessions do
      member do
        post 'update_session'
        post 'create_thrills'
      end
    end

    resources :categories

    resources :aims do
      member do
        put 'invert_active'
        post 'add_new_aim_pro'
      end
    end

    resources :units

    resources :workout_plans do
      member do
        post 'click'
        post 'addWorkOut'
        post 'add_tag'
        post 'copy'
        get 'read_only'
        put 'invert_active'
      end

    end

    resources :workout_days do
      member do
        post 'addExistingExercise'
        post 'add_new_exercise'
        post 'add_tag'
      end

    end

    resources :exercises

    resources :member_area

    get "dashboard" => "member_area#index"

    resources :create_plan_wizard do
      member do
        post 'add_new_day'
        post 'add_new_exercise'
      end
    end

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :country
  belongs_to :user

  accepts_nested_attributes_for :user

  def name
    # setting the name for the admin view
    if (street.to_s.empty? && zip.to_s.empty?)
      @name = "id:" + id.to_s + ";Empty"
    else
      @name = "id:" + id.to_s + ";" + street.to_s + ";" + zip.to_s
    end
  end

  end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  after_create { |admin| admin.send_reset_password_instructions }

  def password_required?
    new_record? ? false : super
  end

end

app/models/aim.rb
class Aim < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :aim_progresses
end

app/models/aim_progress.rb
class AimProgress < ActiveRecord::Base
  belongs_to :aim
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :aims
  belongs_to :unit
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_one :address
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :unit
  belongs_to :user
  has_and_belongs_to_many :workout_days
  has_many :exercises_workout_thrills
  has_many :workout_sessions, :through => :exercises_workout_thrills
end

app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :user
  belongs_to :awardable, :polymorphic => true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :taggable, :polymorphic => true
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  has_one :exercise
  has_many :categories
end

app/models/user.rb
class User < ActiveRecord::Base
  #validates_presence_of :forename
  #validates_presence_of :surname
  #validates_presence_of :date_of_birth
  #validates :gender , :presence=>true

  acts_as_authentic do |config|
    # Add custom conﬁguration options here
    config.crypto_provider = Authlogic::CryptoProviders::MD5

    has_one :address, :dependent => :delete
    has_many :workout_plans
    has_many :workout_sessions
    has_many :aims
    has_many :exercises
    has_many :workout_days
    has_many :points
  end

  def send_registration_mail
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.registration(self).deliver
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

end

app/models/user_session.rb
class UserSession <	Authlogic::Session::Base

  attr_accessor :login, :password

  #returns	session	key
  def	to_key
    [session_key]
  end
end

app/models/workout_day.rb
class WorkoutDay < ActiveRecord::Base
  has_many :tags, :as => :taggable
  has_and_belongs_to_many :exercises
  belongs_to :workout_plan
  belongs_to :user
  has_one :workout_session
end

app/models/workout_plan.rb
class WorkoutPlan < ActiveRecord::Base
    has_many :tags, :as => :taggable
    has_many :workout_days
    belongs_to :user

end

app/models/workout_session.rb
class WorkoutSession < ActiveRecord::Base
  has_many :exercises_workout_thrills, :dependent => :delete_all
  has_many :exercises, :through => :exercises_workout_thrills
  belongs_to :workout_day
  belongs_to :user
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

  before_filter :authenticate

  # GET /exercises
  # GET /exercises.json
  def index
    @exercisesGlobal = Exercise.find_all_by_is_global(true)
    @exercisesByUser = Exercise.find_all_by_user_id(current_user.id)

    unitGlobal = @exercisesGlobal.collect { | e |
      e.unit ? [e.id, e.unit.name] : [e.id, "no Unit specified"]
    }
    @unitGlobal = Hash[*(unitGlobal.flatten)]

    unitByUser = @exercisesByUser.collect { | e |
      e.unit ? [e.id, e.unit.name] : [e.id, "no Unit specified"]
    }
    @unitByUser = Hash[*(unitByUser.flatten)]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @exercisesGlobal }
    end
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
    @exercise = Exercise.find(params[:id])
    @unit = @exercise.unit

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @exercise }
    end
  end

  # GET /exercises/new
  # GET /exercises/new.json
  def new
    @exercise = Exercise.new
    assign_unit_selection_list

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @exercise }
    end
  end

  def assign_unit_selection_list

    @unit_selection_list = Unit.all.collect {|unit| [ unit.name, unit.id ] }
  end

  # GET /exercises/1/edit
  def edit
    @exercise = Exercise.find(params[:id])
    assign_unit_selection_list
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(params[:exercise])
    @exercise.user_id = current_user.id

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'Exercise was successfully created.' }
        format.json { render json: @exercise, status: :created, location: @exercise }
      else
        format.html { render action: "new" }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /exercises/1
  # PUT /exercises/1.json
  def update
    @exercise = Exercise.find(params[:id])

    respond_to do |format|
      if @exercise.update_attributes(params[:exercise])
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise = Exercise.find(params[:id])
    @exercise.destroy

    respond_to do |format|
      format.html { redirect_to exercises_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/aims_helper.rb
module AimsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/exercises/_form.html.erb
<%= form_for(@exercise) do |f| %>
  <% if @exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
      <% @exercise.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :points %><br />
    <%= f.number_field :points %>
  </div>

  <div class="field">
    <%= f.label :unit_id %><br />
    <%= select("exercise", "unit_id", @unit_selection_list,
       {:prompt =>  "Select Unit"  } ) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h1>Editing exercise</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercise %> |
<%= link_to 'Back', exercises_path %>

app/views/exercises/index.html.erb
<h1>Listing exercises </h1>
<hr/>
<h2>Global</h2>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Picture</th>
    <th>Points</th>
    <th>Unit</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @exercisesGlobal.each do |exercise| %>
  <tr>
    <td><%= exercise.name %></td>
    <td><%= exercise.description %></td>
    <td><%= exercise.picture %></td>
    <td><%= exercise.points %></td>
    <td><%= @unitGlobal[exercise.id] %></td>
    <td><%= link_to 'Show', exercise %></td>
    <td><%= link_to 'Edit', edit_exercise_path(exercise) %></td>
    <td><%= link_to 'Destroy', exercise, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
 <hr/>
<h2>Your own Exercises</h2>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Picture</th>
    <th>Points</th>
    <th>Unit</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @exercisesByUser.each do |exercise| %>
      <tr>
        <td><%= exercise.name %></td>
        <td><%= exercise.description %></td>
        <td><%= exercise.picture %></td>
        <td><%= exercise.points %></td>
        <td><%= @unitByUser[exercise.id] %></td>
        <td><%= link_to 'Show', exercise %></td>
        <td><%= link_to 'Edit', edit_exercise_path(exercise) %></td>
        <td><%= link_to 'Destroy', exercise, confirm: 'Are you sure?', method: :delete %></td>
      </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Exercise', new_exercise_path %>

app/views/exercises/new.html.erb
<h1>New exercise</h1>

<%= render 'form' %>

<%= link_to 'Back', exercises_path %>

app/views/exercises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @exercise.name %>
</p>

<p>
  <b>Description:</b>
  <%= @exercise.description %>
</p>

<p>
  <b>Picture:</b>
  <%= @exercise.picture %>
</p>

<p>
  <b>Points:</b>
  <%= @exercise.points %>
</p>

<p>
  <b>Unit:</b>
  <%=
      if !@unit.nil?
        link_to @unit.name, @unit
      end
  %>
</p>


<%= link_to 'Edit', edit_exercise_path(@exercise) %> |
<%= link_to 'Back', exercises_path %>